var danceclasses = {
  KIDS: {
    Monday: [
        {
          index: 0,
          time : '15:30 - 16:30',
          teacher : 'Pauline',
          location: 'Milngavie',
          address: 'WEST RUGBY CLUB, GLASGOW RD. G62 6AQ',
          googleLocation: 'https://google.com',
          lessonName: 'BOOGIE BABEZ – Street',
          info: 'Ages 3 - P2’s',
          sex: 'Boys & Girls',
      },
      {
        index: 1,
        time : '16:45 - 17:45',
        teacher : 'Pauline',
        location: 'Milngavie',
        address: 'WEST RUGBY CLUB, GLASGOW RD. G62 6AQ',
        googleLocation: 'https://google.com',
        lessonName: 'BIGGIE SMALLZ – Girls Street',
        info: 'Ages P3 - P6',
        sex: 'Girls',
    },
  ],
  Friday: [
      {
        index: 0,
        time : '15:30 - 16:30',
        teacher : 'Pauline',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'BOOGIE BABEZ – Street',
        info: 'Ages 3 - P2’s',
        sex: 'Boys & Girls',
    },
    {
      index: 1,
      time : '16:30 - 17:30',
      teacher : 'Pauline',
      location: 'Balloch',
      address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
      googleLocation: 'https://google.com',
      lessonName: 'KOOL KIDZ – Girls Street',
      info: 'Ages P3 - P7',
      sex: 'Girls',
  },
],
},
JUNIORS: {
Monday: [
    {
      index: 0,
      time : '17:45 - 18:45',
      teacher : 'Pauline',
      location: 'Milngavie',
      address: 'WEST RUGBY CLUB, GLASGOW RD. G62 6AQ',
      googleLocation: 'https://google.com',
      lessonName: 'JNR CONTEMPORARY – Contemporary',
      info: 'Ages P3 +',
      sex: 'Boys & Girls',
        },
    ],
    Tuesday: [
        {
          index: 0,
          time : '15:30 - 16:30',
          teacher : 'Paul',
          location: 'Milngavie',
          address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
          googleLocation: 'https://google.com',
          lessonName: 'JNR BOYZ – Street',
          info: 'Ages P5 +',
          sex: 'Boys',
      },
      {
        index: 1,
        time : '20:00 - 21:00',
        teacher : 'Chloe',
        location: 'Milngavie',
        address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
        googleLocation: 'https://google.com',
        lessonName: 'JNR GIRLS – Street',
        info: 'Ages P7 - S3',
        sex: 'Girls',
    },
  ],
    Thursday: [
        {
          index: 0,
          time : '15:45 - 16:45',
          teacher : 'Pauline',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'JNR CONTEMPORARY – Contemporary',
          info: 'Ages P4 +',
          sex: 'Boys & Girls',
      },
  ],
  Friday: [
      {
        index: 0,
        time : '17:30 - 18:30',
        teacher : 'Paul',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'JNR BOYZ – Boys Street',
        info: 'Ages P3 - 7',
        sex: 'Boys',
    },
  ],
  Saturday: [
        {
          index: 0,
          time : '12:45 - 13:30',
          teacher : 'Pauline',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'BEGINNERS TAP',
          info: 'Ages 11+',
          sex: 'Boys & Girls',
      },
      {
        index: 1,
        time : '14:30 - 15:30',
        teacher : 'Erin and Rachael',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'JNR GIRLS - Street',
        info: 'Ages P7 - S3',
        sex: 'Girls',
    },
],
},

SENIORS: {
  Tuesday: [
      {
        index: 0,
        time : '17:00 - 18:00',
        teacher : 'Chloe & Pauline',
        location: 'Milngavie',
        address: 'THE SCOUT HALL, MAIN ST. MILNGAVIE, G62 6BX',
        googleLocation: 'https://google.com',
        lessonName: 'Girls Youth Crew',
        info: 'Ages S3+',
        sex: 'Girls',
    },
    {
      index: 1,
      time : '20:45 - 21:45',
      teacher : 'Pauline',
      location: 'Milngavie',
      address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
      googleLocation: 'https://google.com',
      lessonName: 'LAYDEEZ',
      info: 'adult street fitness',
      sex: 'Women',
    }
  ],
  Thursday: [
      {
        index: 0,
        time : '16:45 - 17:45',
        teacher : 'Paul',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'SNR BOYS STREET SKILLZ',
        info: 'Ages s1 +',
        sex: 'Boys',
    },
  ],
  Saturday: [
        {
          index: 0,
          time : '09:45 - 11:00',
          teacher : 'Paul & Pauline',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'SNR CREATIVE',
          info: 'Creative dance',
          sex: 'Boys & Girls',
      },
      {
        index: 1,
        time : '12:30 - 13:30',
        teacher : 'Erin & Rachel',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'GIRLS YOUTH CREW',
        info: 'Ages s3+',
        sex: 'Girls',
      },
    ]
  },

COMPETITIVE: {
Tuesday: [
    {
      index: 0,
      time : '18:00 - 19:15',
      teacher : 'Paul & Pauline',
      location: 'Milngavie',
      address: 'THE SCOUT HALL, MAIN ST. MILNGAVIE, G62 6BX',
      googleLocation: 'https://google.com',
      lessonName: 'COMPETITION TEAM DANCERS',
      info: 'Competitive Dance',
      sex: 'Boys & Girls',
  },
],
Saturday: [
    {
      index: 0,
      time : '09:45 - 11:00',
      teacher : 'Erin & Rach',
      location: 'Balloch',
      address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
      googleLocation: 'https://google.com',
      lessonName: 'HOODLUMZ CHOREO',
      info: 'Choreography class',
      sex: 'Boys & Girls',
  },
  {
    index: 1,
    time : '11:00 - 12:10',
    teacher : 'Paul & Pauline',
    location: 'Balloch',
    address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
    googleLocation: 'https://google.com',
    lessonName: 'COMPETITION TRAINING',
    info: 'Competitive Dance | The Honeys\' / Hoodlums',
    sex: 'Boys & Girls',
},
],
},

  PRIVATE: {
    Saturday: [
        {
          index: 0,
          time : '14:30 - 15:30',
          teacher : 'Paul',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'Ballet Barre Privates',
          info: 'Ballet',
          sex: 'Mixed',
      },
    ],
    },
}

export default danceclasses
