var danceclasses = {
  KIDS: {
    Monday: [
        {
          index: 0,
          time : '15:30 - 1630',
          teacher : 'Pauline Joseph',
          location: 'Milngavie',
          address: 'WEST RUGBY CLUB, GLASGOW RD. G62 6AQ',
          googleLocation: 'https://google.com',
          lessonName: 'BOOGIE BABEZ – Street',
          info: 'Ages 3 - P2’s | boys & girls',
      },
      {
        index: 1,
        time : '16:45 - 17:45',
        teacher : 'Pauline Joseph',
        location: 'Milngavie',
        address: 'WEST RUGBY CLUB, GLASGOW RD. G62 6AQ',
        googleLocation: 'https://google.com',
        lessonName: 'BIGGIE SMALLZ – Girls Street',
        info: 'Ages P3 - P6 | Girls',
    },
  ],
    Tuesday: [
        {
          index: 0,
          time : '15:30 - 16:30',
          teacher : 'Paul Joseph',
          location: 'Milngavie',
          address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
          googleLocation: 'https://google.com',
          lessonName: 'WEE SKILLZ – Boys Street',
          info: 'Ages P2 - P4 | Boys',
      },
  ],
  Friday: [
      {
        index: 0,
        time : '15:30 - 16:30',
        teacher : 'Pauline Joseph',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'BOOGIE BABEZ – Street',
        info: 'Ages 3 - P2’s | boys & girls',
    },
    {
      index: 1,
      time : '16:30 - 17:30',
      teacher : 'Pauline Joseph',
      location: 'Balloch',
      address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
      googleLocation: 'https://google.com',
      lessonName: 'KOOL KIDZ – Girls Street',
      info: 'Ages P3 - P7 | Girls',
  },
],
},
JUNIORS: {
Monday: [
    {
      index: 0,
      time : '17:45 - 18:45',
      teacher : 'Pauline Joseph',
      location: 'Milngavie',
      address: 'WEST RUGBY CLUB, GLASGOW RD. G62 6AQ',
      googleLocation: 'https://google.com',
      lessonName: 'JNR CONTEMPORARY – Contemporary',
      info: 'Ages P3 + | stretch, lyrical, creative | boys & girls',
        },
    ],
    Tuesday: [
        {
          index: 0,
          time : '16:30 - 17:30',
          teacher : 'Paul Joseph',
          location: 'Milngavie',
          address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
          googleLocation: 'https://google.com',
          lessonName: 'JNR BOYZ – Street',
          info: 'Ages P5 + | Boys',
      },
      {
        index: 1,
        time : '20:00 - 21:00',
        teacher : 'Chloe',
        location: 'Milngavie',
        address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
        googleLocation: 'https://google.com',
        lessonName: 'JNR GIRLS – Street',
        info: 'Ages P7 - S3 | Girls',
    },
  ],
    Thursday: [
        {
          index: 0,
          time : '15:45 - 16:45',
          teacher : 'Pauline Joseph',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'JNR CONTEMPORARY – Contemporary',
          info: 'Ages P4 + | lyrical, gym, creative | boys & girls',
      },
  ],
  Friday: [
      {
        index: 0,
        time : '17:30 - 18:30',
        teacher : 'Paul Joseph',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'JNR BOYZ – Boys Street',
        info: 'Ages P3 - 7 | Boys',
    },
  ],
  Saturday: [
        {
          index: 0,
          time : '12:45 - 13:30',
          teacher : 'Pauline Joseph',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'BEGINNERS TAP',
          info: 'Ages 11+ | Mixed',
      },
      {
        index: 1,
        time : '14:30 - 15:30',
        teacher : 'Erin and Rachael',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'JNR GIRLS - Street',
        info: 'Ages P7 - S3 | Girls',
    },
],
},

SENIORS: {
  Tuesday: [
      {
        index: 0,
        time : '17:00 - 18:00',
        teacher : 'Chloe & Pauline',
        location: 'Milngavie',
        address: 'SCOUT HALL',
        googleLocation: 'https://google.com',
        lessonName: 'Girls Youth Crew',
        info: 'Ages S3+ | Girls',
    },
    {
      index: 1,
      time : '20:45 - 21:45',
      teacher : 'Pauline',
      location: 'Milngavie',
      address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
      googleLocation: 'https://google.com',
      lessonName: 'LAYDEEZ',
      info: 'adult street fitness | Women',
    }
  ],
  Thursday: [
      {
        index: 0,
        time : '16:45 - 17:45',
        teacher : 'Paul',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'SNR BOYS STREET SKILLZ',
        info: 'Ages s1 + | Boys',
    },
  ],
  Saturday: [
        {
          index: 0,
          time : '09:45 - 11:00',
          teacher : 'Paul & Pauline',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'SNR CREATIVE',
          info: 'Creative dance | mixed',
      },
      {
        index: 1,
        time : '12:30 - 13:30',
        teacher : 'Erin & Rachel',
        location: 'Balloch',
        address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
        googleLocation: 'https://google.com',
        lessonName: 'GIRLS YOUTH CREW',
        info: 'Ages s3+ | Girls',
      },
    ]
  },

COMPETITIVE: {
Tuesday: [
    {
      index: 0,
      time : '18:00 - 19:15',
      teacher : 'Paul & Pauline',
      location: 'Milngavie',
      address: 'ALLANDER LEISURE CENTRE, MILNGAVIE RD. G61 3DF',
      googleLocation: 'https://google.com',
      lessonName: 'COMPETITION TEAM DANCERS',
      info: 'Competitive Dance | mixed',
  },
],
Saturday: [
    {
      index: 0,
      time : '09:45 - 11:00',
      teacher : 'Erin & Rach',
      location: 'Balloch',
      address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
      googleLocation: 'https://google.com',
      lessonName: 'HOODLUMZ CHOREO',
      info: 'Choreography class',
  },
  {
    index: 1,
    time : '11:00 - 12:10',
    teacher : 'Paul & Pauline',
    location: 'Balloch',
    address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
    googleLocation: 'https://google.com',
    lessonName: 'COMPETITION TRAINING',
    info: 'Competitive Dance | The Honeys\' / Hoodlums',
},
],
},

  PRIVATE: {
    Saturday: [
        {
          index: 0,
          time : '14:30 - 15:30',
          teacher : 'Paul',
          location: 'Balloch',
          address: 'THE LENNOX HALL, MAIN ST. JAMESTOWN, BALLOCH G83 8AZ',
          googleLocation: 'https://google.com',
          lessonName: 'Ballet Barre Privates',
          info: 'Ballet',
      },
    ],
    },
}

export default danceclasses
